### ISSUE TITLE
`client.MessagesApi.ListMessages` Parameter [dateFrom] value is invalid

### ISSUE THREAD

**Issue by grokify** [grokify/go-ringcentral-client#19]
**Description**

Setting the `dateFrom` as follows results in the error below.

* SDK: `client.MessagesApi.ListMessages(context.Background(), "~", "~", map[string]interface{}{"dateTime": time.Now()})`
* API:  `GET /restapi/v1.0/account/~/extension/~/message-store`

```
Status: 400 Bad Request

{
  "errorCode" : "InvalidParameter",
  "message" : "Parameter [dateFrom] value is invalid",
  "errors" : [ {
    "errorCode" : "CMN-101",
    "message" : "Parameter [dateFrom] value is invalid",
    "parameterName" : "dateFrom"
  } ],
  "parameterName" : "dateFrom"
}
```

**Cause**

Investigation shows the time is being converted to:

`2018-01-01 00:00:00 +0000 UTC` which is not the expected ISO-8601 / RFC-3339 time.

The relevant code in `messages_api.go` for `ListMessages` API is:

```go
	if localVarTempParam, localVarOk := localVarOptionals["dateFrom"].(time.Time); localVarOk {
		localVarQueryParams.Add("dateFrom", parameterToString(localVarTempParam, ""))
	if localVarTempParam, localVarOk := localVarOptionals["dateTo"].(time.Time); localVarOk {
		localVarQueryParams.Add("dateTo", parameterToString(localVarTempParam, ""))
```

`api_client.go:func parameterToString(obj interface{}, collectionFormat string) string {`

**Additional Info**

The Swagger spec shows:

```yaml
          -
            name: "dateFrom"
            in: "query"
            description: "The start datetime for resulting messages in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z. The default value is dateTo minus 24 hours"
            required: false
            type: "string"
            format: "date-time"
          -
            name: "dateTo"
            in: "query"
            description: "The end datetime for resulting messages in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z. The default value is current time"
            required: false
            type: "string"
            format: "date-time"
```
