### ISSUE TITLE
GlipPersonInfo is missing `jobTitle` and `location` properties

### ISSUE THREAD

**Issue by grokify** [grokify/go-ringcentral-client#34]
`GlipPersonInfo` needs properties for `jobTitle` and `location`.

This is a Swagger spec issue which needs the following:

```yaml
    GlipPersonInfo:
      type: "object"
      required:
        - "id"
      properties:
        jobTitle:
          type: "string"
          description: "Job title of a user"
        location:
          type: "string"
          description: "Location of a user"
```
