### ISSUE TITLE
Name collisions with new RingCentral OpenAPI 2.0 spec and OpenAPI Generator 4.0.0

### ISSUE THREAD

**Issue by grokify** [grokify/go-ringcentral-client#35]
Attempting to build the SDK using the new RingCentral OpenAPI 2.0 spec and OpenAPI Generator 4.0.0 SNAPSHOT (openapi-generator-cli-4.0.0-20190302.141844-340.jar) results in the following collisions.

```bash
$ go run get_me.go 
../../ringcentral/api_sms_and_mms.go:42:6: DeleteMessageOpts redeclared in this block
	previous declaration at ../../ringcentral/api_internal_messages.go:135:6
../../ringcentral/api_sms_and_mms.go:128:6: DeleteMessagesByFilterOpts redeclared in this block
	previous declaration at ../../ringcentral/api_internal_messages.go:221:6
../../ringcentral/api_sms_and_mms.go:218:6: GetMessageAttachmentByIdOpts redeclared in this block
	previous declaration at ../../ringcentral/api_internal_messages.go:311:6
../../ringcentral/api_sms_and_mms.go:314:6: ListMessagesOpts redeclared in this block
	previous declaration at ../../ringcentral/api_internal_messages.go:407:6
../../ringcentral/api_sms_and_mms.go:657:6: SyncMessagesOpts redeclared in this block
	previous declaration at ../../ringcentral/api_internal_messages.go:657:6
../../ringcentral/api_sms_and_mms.go:657:6: too many errors
```

This occurs because the API endpoint is tagged with multiple tags and OpenAPI Generator creates a non-namespaced options struct for each namespaced endpoint.

```yaml
  /restapi/v1.0/account/{accountId}/extension/{extensionId}/message-store/{messageId}:
    get:
      tags:
      - Fax
      - SMS and MMS
      - Internal Messages
```
